### PR TITLE
fix to run on svelte setup 

### LINKED ISSUE #53: runtime error on svelte env
### What browser client(s) are you seeing the issue on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What devices platform(s) are you seeing the issue on?

- [ ] Desktop
- [ ] Mobile

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Which version of auro-templates do you have installed?

_No response_

### Reproducible on the Auro doc site

- [ ] I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).

### Exit criteria (To be determined by the Auro team)

_No response_

### PR DESCRIPTION
**Pull request by sun-mota**
# Alaska Airlines Pull Request

- fix not to have error on svelte setup
- fix to work with formkit dropdown

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

## Summary by Sourcery

Refactors the auro-drawer component to use Floating UI for positioning and behavior, adds new properties for controlling the drawer's appearance and behavior, and updates the component's template and styles.

New Features:
- Adds support for different drawer placements (left, right, top, bottom).
- Introduces a fullscreen breakpoint to switch to fullscreen mode on mobile devices.
- Adds a nested property to allow the drawer to be placed inside a container.
- Adds an unformatted property to allow for full customization of content within the scope of the window.
- Adds a modal property to lock a user into interacting with the drawer.
- Adds a size property to control the size of the drawer bib to `sm`, `md`, `lg`

Tests:
- Adds tests for new features and properties, including placement, fullscreen breakpoint, nested, unformatted, modal, and size.
- Adds tests for auro-drawer gets open by triggerElement
- Adds tests for unformatted auro-drawer does not render header or footer
- Adds tests for auro-drawer renders a close icon and closes on click
- Adds tests for sm auro-drawer is smaller than md auro-drawer
- Adds tests for auro-drawer covers the fullscreen in mobile view

### CODE REVIEW

File: src/auro-floater.js [hunk 1]
```diff
@@ -48,8 +48,7 @@ export class AuroFloater extends LitElement {
        * The element to focus when the drawer is closed.
        */
       triggerElement: {
-        attribute: false,
-        type: HTMLElement
```
Comment (jordanjones243) [inline src/auro-floater.js:52]: Why did you remove the type?

**Review by jordanjones243 — CHANGES_REQUESTED** [review]

File: src/auro-floater.js (hunk 1 above)
Comment (sun-mota) [reply src/auro-floater.js:52]: HTMLELement is not getting recognized in svelte SSR setup

File: src/util/floatingUI.js [hunk 2]
```diff
@@ -258,23 +258,25 @@ export default class AuroFloatingUI {
     this.clickHandler = (evt) => {
       if ((!evt.composedPath().includes(this.element.trigger) &&
         !evt.composedPath().includes(this.element.bib)) ||
-        evt.composedPath().includes(this.element.bib.backdrop)) {
-        const existedVisibleFloatingUI = document.expandedAuroDropdown || document.expandedAuroFormkitDropdown || document.expandedAuroFloater;
+        (this.element.bib.backdrop && evt.composedPath().includes(this.element.bib.backdrop))) {
+        const existedVisibleFloatingUI = document.expandedAuroFormkitDropdown || document.expandedAuroFloater;
+
         if (existedVisibleFloatingUI && existedVisibleFloatingUI.element.isPopoverVisible) {
+          // if something else is open, clost that
```
Comment (jordanjones243) [inline src/util/floatingUI.js]: Either remove this comment or fix spelling of "close"

**Review by jordanjones243 — APPROVED** [review]
