### PR TITLE
fix: remove bib on disconnect in auro-floater

### LINKED ISSUE #60: bib is not getting removed when the drawer element gets detached
### What browser client(s) are you seeing the issue on?

- [x] Firefox
- [x] Chrome
- [x] Safari
- [x] Microsoft Edge

### What devices platform(s) are you seeing the issue on?

- [x] Desktop
- [x] Mobile

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Which version of auro-templates do you have installed?

_No response_

### Reproducible on the Auro doc site

- [x] I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).

### Exit criteria (To be determined by the Auro team)

_No response_

### PR DESCRIPTION
**Pull request by sun-mota**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

closes #60 

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

## Summary by Sourcery

Fix the disconnect method in auro-floater to properly handle the bib element and update dependency versions

Bug Fixes:
- Ensure the bib element is correctly reappended to the shadow root when disconnecting the floater

Enhancements:
- Update various Auro design system package dependencies to their latest versions

### CODE REVIEW

File: src/util/floatingUI.js [hunk 1]
```diff
@@ -547,16 +547,23 @@ export default class AuroFloatingUI {
...
-    // Remove event & keyboard listeners
-    if (this.element?.trigger) {
-      this.element.trigger.removeEventListener('keydown', this.handleEvent);
-      this.element.trigger.removeEventListener('click', this.handleEvent);
-      this.element.trigger.removeEventListener('mouseenter', this.handleEvent);
-      this.element.trigger.removeEventListener('mouseleave', this.handleEvent);
-      this.element.trigger.removeEventListener('focus', this.handleEvent);
-      this.element.trigger.removeEventListener('blur', this.handleEvent);
+
+    if (this.element) {
```
Comment (chrisfalaska) [inline src/util/floatingUI.js]: Maybe an early return here?

`if (!this.element) return;`

File: src/util/floatingUI.js [hunk 2]
```diff
@@ -547,16 +547,23 @@ export default class AuroFloatingUI {
...
+
+      // Remove event & keyboard listeners
+      if (this.element?.trigger) {
+        this.element.trigger.removeEventListener('keydown', this.handleEvent);
+        this.element.trigger.removeEventListener('click', this.handleEvent);
+        this.element.trigger.removeEventListener('mouseenter', this.handleEvent);
+        this.element.trigger.removeEventListener('mouseleave', this.handleEvent);
+        this.element.trigger.removeEventListener('focus', this.handleEvent);
+        this.element.trigger.removeEventListener('blur', this.handleEvent);
+      }
```
Comment (chrisfalaska) [inline src/util/floatingUI.js]: Maybe something like this?

```
if (this.element.trigger) {
    const events = ['keydown', 'click', 'mouseenter', 'mouseleave', 'focus', 'blur'];
    events.forEach(eventType => 
      this.element.trigger.removeEventListener(eventType, this.handleEvent)
    );
  }
```

**Review by chrisfalaska — CHANGES_REQUESTED** [review]

**Review by chrisfalaska — APPROVED** [review]
