### PR TITLE
fix: update focus trap to always have a relevant list of focusable elements

### LINKED ISSUE #69: [due 5/23] `auro-drawer` does not support dynamic DOM change on content slot
Reported by Booking team

### What browser client(s) are you seeing the issue on?

- [x] Firefox
- [x] Chrome
- [x] Safari
- [x] Microsoft Edge

### What devices platform(s) are you seeing the issue on?

- [x] Desktop
- [ ] Mobile

### Steps to reproduce

1. when the content has any focusable elements which can change disabled or tabindex state dynamically,
drawer does not update the focusable elements array. So that some of elements would never get focus with TAB key or always get focus regardless tabindex/disabled state.
2. when the content has a newly added focusable element, drawer does not update the focusable elements array. So that newly added elements would never get focus.

### Expected behavior

_No response_

### Which version of auro-templates do you have installed?

_No response_

### Reproducible on the Auro doc site

- [ ] I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).

### Exit criteria (To be determined by the Auro team)

_No response_

### PR DESCRIPTION
**Pull request by StephenRiosDev**
fix: update focus trap to always have a relevant list of focusable elements

- Removed focus trap functionality from base component
- Abstracted focus trapping into composable service
- Improved robustness of focus trap functionality

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Checklist:

- [X] My update follows the CONTRIBUTING guidelines of this project
- [X] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

## Summary by Sourcery

Abstract focus trapping into a reusable service, integrate it into the AuroDrawerContent component to improve focus management, and update test coverage thresholds.

Bug Fixes:
- Fix focus trap to always target the correct set of focusable elements in the drawer component.

Enhancements:
- Extract focus trap logic from the drawer component into a new standalone FocusTrap service.
- Refactor AuroDrawerContent to leverage the FocusTrap service and remove legacy focus management code.

Build:
- Lower test coverage thresholds in Web Test Runner configuration from 80% to 70%.

### CODE REVIEW

File: src/util/FocusTrap.js [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+  _onBookendFocusEnd = () => {
+    if (this.tabDirection === 'forward') {
+      this._focusFirstElement();
+    }
+  };
+
+  _getFocusableElements() {
+
+    // Get all focusable elements within the container based on the FOCUSABLE_SELECTORS constant
+    let results = Array.from(this.container.querySelectorAll(FOCUSABLE_SELECTORS.join(',')));
```
[the remark this answers is not in the document]
Comment (StephenRiosDev) [reply src/util/FocusTrap.js:101]: Since elements in the shadow root won't be in the natural tab order, and this component updates tab position on focus of the book ends, this means elements in the shadow root will be outside of the natural tab index scope, and also cannot be added to the list of focusable elements in the actual order they appear in the DOM, which means we can't guarantee that they'll be focus on their actual order.

This is a known and acceptable limitation of this composable service.

File: web-test-runner.config.mjs [hunk 2]
```diff
@@ -3,10 +3,10 @@ export default {
   nodeResolve: true,
   coverageConfig: {
     threshold: {
-      statements: 80,
-      branches: 75,
-      functions: 80,
-      lines: 80
```
[the remark this answers is not in the document]
Comment (StephenRiosDev) [reply web-test-runner.config.mjs:9]: Service will be moved to another repo for broad consumption. Unit tests will be written to test this service in isolation at that time. For now, test thresholds reduce to allow for release to waiting teams to fulfill urgent request.

File: src/auro-drawer-content.js [hunk 3]
```diff
@@ -92,54 +68,18 @@ export class AuroDrawerContent extends LitElement {
...
-
-    this.shadowRoot.querySelector('.wrapper').focus();
-  }
-
-  handleWrapperFocus() {
-    this.focusables[this.focusIndex].focus();
-  }
-
   handleWrapperTransitionEnd() {
     if (this.visible) {
```
Comment (chrisfalaska) [inline src/auro-drawer-content.js]: Does it make sense to add an early `return`?

File: src/auro-drawer-content.js [hunk 4]
```diff
@@ -92,54 +68,18 @@ export class AuroDrawerContent extends LitElement {
...
+      this.shadowRoot.querySelector('.wrapper').focus();
     }
   }
 
   updated(changedProperties) {
     if (changedProperties.has('visible')) {
       if (this.visible) {
+        if (!this.focusTrap) {
+          this.focusTrap = new FocusTrap(this);
+        }
```
Comment (chrisfalaska) [inline src/auro-drawer-content.js:81]: Maybe some error handling?

```
if (!this.focusTrap) {
  try {
    this.focusTrap = new FocusTrap(this);
  } catch (error) {
    console.warn('Focus trap initialization failed:', error);
  }
}
```

File: src/auro-drawer-content.js [hunk 5]
```diff
@@ -150,21 +90,30 @@ export class AuroDrawerContent extends LitElement {
           this.prevActiveElement.focus();
           this.prevActiveElement = undefined;
         }
+
+        if (this.focusTrap) {
+          this.focusTrap.disconnect();
+          this.focusTrap = null;
```
Comment (chrisfalaska) [inline src/auro-drawer-content.js:95]: Same here, maybe?

```
try {
  this.focusTrap.disconnect();
  } catch (error) {
    console.warn('Focus trap cleanup failed:', error);
  }
}
```

**Review by chrisfalaska — CHANGES_REQUESTED** [review]

File: src/auro-drawer-content.js (hunk 3 above)
Comment (StephenRiosDev) [reply src/auro-drawer-content.js]: This whole section actually got removed since it wasn't required any more.

Although, if this code still existed, I think an early return wouldn't make sense here. By default this function will call `return void` right after line 131. We typically only need early or explicit returns when there are other lines of code that may execute after a given line in the same function and we don't want them to, and/or if, of course, we have a value to return.

File: src/auro-drawer-content.js (hunk 4 above)
Comment (StephenRiosDev) [reply src/auro-drawer-content.js:81]: Personally, I'm not really a fan of try/catch outside of async code. 

Why? 

In my opinion, if something inside FocusTrap is going to fail, it should be handled inside FocusTrap. That is to say, that focus trap should be written well enough to handle it's own failures, and let the developer/user know about them in a way that makes sense.

So what about async code changes my opinion on this?

Well, because async code may call an API, become multi-threaded and kick off multiple threads of code that may fail at any point, and fail in any number of places, or even multiple places. A try/catch lets us catch those errors, even if they are handled externally, and fail gracefully for the user.

So why don't I feel like this applies to single-threaded code like standing up services?

For me, it comes down to a conversation I've wanted to have in our engineering sync-up for a while now: developer vs. user experience.

If single-threaded code fails, it's almost always because there's an actual issue with the code, which is the case here. If the creation of a new instance of FocusTrap fails, that should be a very visible and obvious break in execution so that developers can notice and address the issue. In this case, we don't want to fail gracefully, as it may cause the issue to be missed before release, and since, if this happens, the page is technically broken, it should break execution as well.

In the case of adding a try/catch block with only a `console.warn` in place, page execution would continue as normal, and if a developer is not looking at the console, they may think that all is well.

You could alternatively use `throw new Error()` instead of console.warn, but again, I feel like it should be the responsibility of the FocusTrap class to handle it's own error states and throw accordingly when it needs to.

What do you think?

File: src/auro-drawer-content.js (hunk 5 above)
Comment (StephenRiosDev) [reply src/auro-drawer-content.js:95]: Same as the above comment.

**Review by chrisfalaska — DISMISSED** [review]
Looks great!

File: src/auro-drawer-content.js (hunk 3 above)
Comment (chrisfalaska) [reply src/auro-drawer-content.js]: Sorry, i clicked the wrong line.

I meant line 71 in your current file.

```
if (!this.visible) return;
```

**Review by chrisfalaska — APPROVED** [review]
